#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
from pathlib import Path
from collections import Counter

ALLOWED = ["chair", "table", "sofa", "lamp", "plant", "cabinet"]
LABEL_MAP = {
    "chair": "chair",
    "table": "table",
    "sofa": "sofa",
    "lamp": "lamp",
    "plant": "plant",
    "cabinet": "cabinet",
}

def patch_manifest(manifest_path: Path, condition: str):
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    for entry in manifest.get("predictions", []):
        pred = entry.get("prediction", {})
        raw_objects = pred.get("objects", [])

        counts = Counter()
        for obj in raw_objects:
            cat = obj.get("category")
            mapped = LABEL_MAP.get(cat)
            if mapped in ALLOWED:
                counts[mapped] += 1

        object_counts = {cat: int(counts.get(cat, 0)) for cat in ALLOWED}
        pred["objects"] = [
            {"category": cat, "count": count, "attributes": []}
            for cat, count in object_counts.items()
            if count > 0
        ]
        pred["object_counts"] = object_counts
        pred["attributes"] = []
        pred["relations"] = []
        pred["scene_type"] = "room"

    manifest["export"] = {
        "source_system": "university_server",
        "source_hostname": "elm43",
        "source_root": "~/workspace/SpatialLM",
        "command": "python inference.py -d object -p <corrupted_ply> -o <scene_id>.txt --model_path ysmao/SpatialLM1.1-Qwen-0.5B-ARKitScenes-SFT",
        "created_at_utc": "2026-04-24T12:30:00Z",
        "model_name": "ysmao/SpatialLM1.1-Qwen-0.5B-ARKitScenes-SFT",
        "notes": f"SpatialLM {condition} validation outputs converted from raw Bbox text files."
    }
    manifest["notes"] = (
        f"Converted from SpatialLM Bbox(...) text outputs on {condition} PLY files. "
        "This export contains object boxes only; relations are empty and scene_type is room."
    )

    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"patched {manifest_path}")


def patch_metadata(metadata_path: Path, condition: str):
    condition_name = {
        "mild_corruption": "mild",
        "medium_corruption": "medium",
        "severe_corruption": "severe",
        "clean": "clean",
    }.get(condition, condition)

    metadata = {
        "schema_name": "external_baseline_run_metadata",
        "schema_version": "1.0",
        "baseline_id": "spatiallm_import",
        "baseline_label": "SpatialLM imported structured outputs",
        "kind": "imported_structured",
        "dataset": "arkitscenes",
        "split": "Validation",
        "condition": condition,
        "corruption": {
            "preset": condition,
            "severity": condition_name,
            "family": "coordinate_perturbation_and_quantization",
            "notes": "SpatialLM input generated by coordinate noise and quantization on ARKitScenes 3DOD meshes."
        },
        "export": {
            "source_system": "university_server",
            "source_hostname": "elm43",
            "source_root": "~/workspace/SpatialLM",
            "command": "python inference.py -d object -p <corrupted_ply> -o <scene_id>.txt --model_path ysmao/SpatialLM1.1-Qwen-0.5B-ARKitScenes-SFT",
            "created_at_utc": "2026-04-24T12:30:00Z",
            "model_name": "ysmao/SpatialLM1.1-Qwen-0.5B-ARKitScenes-SFT",
            "notes": f"SpatialLM {condition} validation outputs converted from raw Bbox text files."
        },
        "notes": f"{condition} SpatialLM outputs for 10 ARKitScenes validation scenes."
    }

    metadata_path.write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"patched {metadata_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--metadata", required=True)
    ap.add_argument("--condition", required=True)
    args = ap.parse_args()

    patch_manifest(Path(args.manifest), args.condition)
    patch_metadata(Path(args.metadata), args.condition)


if __name__ == "__main__":
    main()
